on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Go 1.22
      uses: actions/setup-go@v1
      with: 
        go-version: 1.22      

    - name: Build app 
      run: go build -o "chat_gpt_t_bot" .

    - name: Copy app via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        source: "chat_gpt_t_bot"
        target: "~/tbot"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: |          
          cd ~
          set T_BOT_TEST_URI ${{ secrets.T_BOT_URI }}
          echo "$T_BOT_TEST_URI" >> test.txt
          ${{ secrets.HOMEDIR }}/service.sh restart
      
